### ISSUE TITLE
[Umbrella Issue] CLI usability improvements

### ISSUE THREAD

**Issue by yue9944882** [open-cluster-management-io/clusteradm#133]
- __Comprehensive `clusteradm get ..` command__:
  - [x] get clusters: 
    - https://github.com/open-cluster-management-io/clusteradm/pull/124
  - [x] get addons: 
    - https://github.com/open-cluster-management-io/clusteradm/pull/103
    - https://github.com/open-cluster-management-io/clusteradm/pull/129
  - [x] get works:
    - https://github.com/open-cluster-management-io/clusteradm/pull/131
  - [x] get hub-info: 
    - https://github.com/open-cluster-management-io/clusteradm/pull/128
  - [ ] get klusterlet-info: 
  - [x] get clustersets:
    - https://github.com/open-cluster-management-io/clusteradm/pull/124
  - [ ] get placements:
  - [ ] general `-o [*table|tree|yaml]` printers
  
- __Clusterset operatibility__:
   - [x] create: https://github.com/open-cluster-management-io/clusteradm/pull/123
   - [x] add cluster/bind namespace: https://github.com/open-cluster-management-io/clusteradm/pull/126
   - [ ] remove cluster
   - [ ] unbind
 
- __Version mgmt / Upgrading__:
  - [x] https://github.com/open-cluster-management-io/clusteradm/pull/119
  
- __Proxy / tunneling__:
  - [ ] proxy health: https://github.com/open-cluster-management-io/clusteradm/pull/90
  - [ ] proxy tunnel: (creating tunnels for kubectl-access to the managed clusters)
    - create
    - connect
    - delete
   - [ ] proxy stats: (collecting stats such as in-use bandwidth, connection counts, etc.)

- __Addon management__:
  - [x] enable/disable: https://github.com/open-cluster-management-io/clusteradm/pull/101
  
- __Miscs__:
  - [ ] unjoin cluster: (removing registered managed clusters from the hub neatly)

**Comment by qiujian16** [comment]
maybe also add create/delete work command?

**Comment by ycyaoxdu** [comment]
now we use command `clusteradm clusterset set` to move one cluster from clusterset1 to  clusterset2 #153

**Comment by ycyaoxdu** [comment]
added command `clusteradm delete clusterset` #154
